services:
  meteo-bot:
    image: ghcr.io/sknarovs/lvgmc-bot:main
    container_name: meteo-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_PATH=/app/data/meteobot.db
    volumes:
      - ./data:/app/data